"""auth changes

Revision ID: 61fcc5dce37b
Revises: 88e04749e398
Create Date: 2026-03-29 18:28:11.888396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61fcc5dce37b"
down_revision: Union[str, Sequence[str], None] = "88e04749e398"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.add_column("bookings", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_bookings_user_id"), "bookings", ["user_id"], unique=False)
    op.create_foreign_key(
        None, "bookings", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("stores", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_stores_owner_id"), "stores", ["owner_id"], unique=False)
    op.create_foreign_key(
        None, "stores", "users", ["owner_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stores", type_="foreignkey")
    op.drop_index(op.f("ix_stores_owner_id"), table_name="stores")
    op.drop_column("stores", "owner_id")
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_index(op.f("ix_bookings_user_id"), table_name="bookings")
    op.drop_column("bookings", "user_id")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
