"""add store hours and bookings

Revision ID: 88e04749e398
Revises: 36f9a8ee5a67
Create Date: 2026-03-13 15:59:33.781824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88e04749e398"
down_revision: Union[str, Sequence[str], None] = "36f9a8ee5a67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_hours",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("open_time", sa.Time(), nullable=False),
        sa.Column("close_time", sa.Time(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_store_hours_store_id"), "store_hours", ["store_id"], unique=False
    )
    op.add_column(
        "bookings", sa.Column("start_time", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "bookings", sa.Column("end_time", sa.DateTime(timezone=True), nullable=False)
    )
    op.drop_column("bookings", "booking_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "booking_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("bookings", "end_time")
    op.drop_column("bookings", "start_time")
    op.drop_index(op.f("ix_store_hours_store_id"), table_name="store_hours")
    op.drop_table("store_hours")
    # ### end Alembic commands ###
