"""description added for services

Revision ID: c27ccf7f6c35
Revises: 962e94f9b822
Create Date: 2026-03-13 15:15:19.976854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c27ccf7f6c35"
down_revision: Union[str, Sequence[str], None] = "962e94f9b822"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services", sa.Column("description", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "description")
    # ### end Alembic commands ###
